<a href="https://colab.research.google.com/github/SandeepKumar080/Deep_Learning/blob/main/Loss_Coss_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
y_predicted = np.array([0,1,0,1,1,1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5,0.6,0.3,0.2,0.1,0.9])

In [ ]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [ ]:
mae(y_predicted, y_true)

Total error is: 4.6
Mean absolute error is: 0.45999999999999996


np.float64(0.45999999999999996)

In [ ]:
np.abs(y_predicted-y_true)

array([0.3, 0.3, 1. , 1. , 0.5, 0.4, 0.7, 0.2, 0.1, 0.1])

In [ ]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.45999999999999996)

In [ ]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [ ]:
mae_np(y_predicted, y_true)

np.float64(0.45999999999999996)

In [ ]:
np.log([0])

<ipython-input-10-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [ ]:
epsilon = 1e-15

In [ ]:
np.log([1e-15])

array([-34.53877639])

In [ ]:
y_predicted

array([0, 1, 0, 1, 1, 1, 1, 0, 0, 1])

In [ ]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1e-15,
 np.int64(1),
 1e-15,
 np.int64(1),
 np.int64(1),
 np.int64(1),
 np.int64(1),
 1e-15,
 1e-15,
 np.int64(1)]

In [ ]:
1-epsilon

0.999999999999999

In [ ]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[1e-15,
 0.999999999999999,
 1e-15,
 0.999999999999999,
 0.999999999999999,
 0.999999999999999,
 0.999999999999999,
 1e-15,
 1e-15,
 0.999999999999999]

In [ ]:
y_predicted_new = np.array(y_predicted_new)

In [ ]:
np.log(y_predicted_new)

array([-3.45387764e+01, -9.99200722e-16, -3.45387764e+01, -9.99200722e-16,
       -9.99200722e-16, -9.99200722e-16, -9.99200722e-16, -3.45387764e+01,
       -3.45387764e+01, -9.99200722e-16])

In [ ]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(15.888077020887973)

In [ ]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [ ]:
log_loss(y_true, y_predicted)

np.float64(15.888077020887973)

In [ ]:
#Without Numpy
def mse(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += (yp - yt) ** 2
    mse_value = total_error / len(y_predicted)
    return mse_value

print(mse(y_predicted, y_true))

0.31399999999999995


In [ ]:
#With Numpy
def mse_np(y_predicted, y_true):
    return np.mean((y_predicted - y_true) ** 2)

print(mse_np(y_predicted, y_true))

0.31399999999999995
